### ISSUE TITLE
ground true cIRM and est cIRM not pair

### ISSUE THREAD

**Issue by yezhangyinge** [RookieJunChen/Inter-SubNet#3]
great job!
But I found that when training the cIRM will using drop_band=2, but the validating will not using drop_band? why?and how to fix this problem?

**Comment by RookieJunChen** [comment]
This drop_band is a continuation of the strategy in FullSubNet: during training, we can drop some subbands in order to reduce the computational and memory pressure on the GPU, which does not affect the performance of the final model too much.  At inference,  to get the complete speech， we do not use the drop_band strategy.
If you want to train without the drop_band strategy, just set `num_groups_in_drop_band` to 1.

**Comment by yezhangyinge** [comment]
Thanks for you reply! I had already reproduced your work, the result on validating dataset is really impressive. And I try my best to download the test dataset(noreverb/reverb) from official website of DNS challenge but it doesn't work, so could you please offer me the test data. Thank you so much.

**Comment by RookieJunChen** [comment]
Could you offer me your email? I will send the test dataset to you through the email.

**Comment by yezhangyinge** [comment]
ok, my email is yezhangyinge@gmail.com. Thank you so much!
